# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: golang

# Set the golang version to 1,11
golang:
    - "1.12"
    - "1.13"

install:
    go get -d  -u ./...

script:
    - make && make ci-test
